import requests
import os
import re
from datetime import datetime, timezone

# --- CONFIGURATION ---
SOURCE_LISTS_FILE = "IncludedLists.md"
LOCAL_WHITELIST_FILE = "whitelist.md"
OUTPUT_FILE = "PrivacyShield.txt"

def parse_source_lists(file_path: str) -> tuple[list[str], list[str]]:
    """
    Parses the Markdown file to extract blocklist and whitelist URLs.
    This version is more robust against formatting inconsistencies.
    
    Returns:
        A tuple containing two lists: (blocklist_urls, whitelist_urls).
    """
    blocklist_urls, whitelist_urls = [], []
    current_section = None
    url_pattern = re.compile(r'\((https?://[^\)]+)\)')

    print(f"Reading source lists from: {file_path}")
    if not os.path.exists(file_path):
        print(f"  -> FATAL: Source file '{file_path}' not found!")
        return [], []

    with open(file_path, 'r') as f:
        for line in f:
            clean_line = line.strip().lower()
            
            # Use forgiving matching for section headers
            if clean_line.startswith('## block list'):
                current_section = "block"
                print("--> Found Block Lists section")
                continue
            if clean_line.startswith('## white list'):
                current_section = "white"
                print("--> Found White List section")
                continue

            # If in a section, find URLs in list items
            if current_section and line.strip().startswith('-'):
                match = url_pattern.search(line)
                if match:
                    url = match.group(1)
                    print(f"    - Extracted URL: {url}")
                    if current_section == "block":
                        blocklist_urls.append(url)
                    elif current_section == "white":
                        whitelist_urls.append(url)
                        
    print(f"\nFound {len(blocklist_urls)} blocklist sources.")
    print(f"Found {len(whitelist_urls)} whitelist sources.")
    return blocklist_urls, whitelist_urls

def process_line(line: str) -> str | None:
    """Cleans up a single line from a blocklist or whitelist source."""
    if '#' in line:
        line = line.split('#', 1)[0]
    line = line.strip()
    if ' ' in line or '\t' in line:
        parts = line.split()
        if len(parts) > 1 and not parts[0].startswith('#'):
            line = parts[1]
    if not line or line in ['0.0.0.0', '127.0.0.1', 'localhost', '::1']:
        return None
    return line.lower()

def fetch_domains_from_urls(urls: list[str]) -> set[str]:
    """Fetches content from a list of URLs and returns a set of processed domains."""
    domain_set = set()
    for url in urls:
        try:
            print(f"  Fetching: {url}")
            response = requests.get(url, timeout=30)
            response.raise_for_status()
            for line in response.text.splitlines():
                clean_domain = process_line(line)
                if clean_domain:
                    domain_set.add(clean_domain)
        except requests.RequestException as e:
            print(f"    -> WARNING: Failed to fetch {url}. Reason: {e}")
    return domain_set

def get_local_whitelist(file_path: str) -> set[str]:
    """Fetches whitelisted domains from a local file."""
    if not os.path.exists(file_path):
        print(f"Local whitelist not found at '{file_path}', skipping.")
        return set()
    whitelisted_domains = set()
    with open(file_path, 'r') as f:
        for line in f:
            clean_domain = process_line(line)
            if clean_domain:
                whitelisted_domains.add(clean_domain)
    print(f"Loaded {len(whitelisted_domains)} domains from local whitelist '{file_path}'.")
    return whitelisted_domains

def main():
    """Main function to run the entire update process."""
    print("--- Starting Blocklist Update Process ---")
    
    blocklist_urls, whitelist_urls = parse_source_lists(SOURCE_LISTS_FILE)
    if not blocklist_urls:
        print("\nFATAL: No blocklist URLs were found. Exiting to prevent creating an empty file.")
        return # Exit early if no sources are found

    print("\n--- Fetching Blocklists ---")
    blocked_domains = fetch_domains_from_urls(blocklist_urls)
    print(f"\nTotal unique domains from blocklists: {len(blocked_domains)}")

    print("\n--- Fetching Whitelists ---")
    remote_whitelist = fetch_domains_from_urls(whitelist_urls)
    local_whitelist = get_local_whitelist(LOCAL_WHITELIST_FILE)
    
    final_whitelist = remote_whitelist.union(local_whitelist)
    print(f"\nTotal unique domains in combined whitelist: {len(final_whitelist)}")

    final_blocklist = sorted(list(blocked_domains - final_whitelist))
    print(f"Total domains after applying whitelist: {len(final_blocklist)}")

    print(f"\nWriting {len(final_blocklist)} domains to {OUTPUT_FILE}...")
    with open(OUTPUT_FILE, 'w') as f:
        f.write("# PrivacyShield Blocklist\n")
        f.write(f"# Generated by GitHub Actions on: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S %Z')}\n")
        f.write(f"# Total Domains: {len(final_blocklist)}\n")
        f.write("#\n")
        for domain in final_blocklist:
            f.write(f"{domain}\n")

    print("\n--- Process Complete ---")

if __name__ == "__main__":
    main()```


